#!/bin/sh

berkas_index="/mnt/usb/ugai/install/index.txt"

# check whether there is a command to create an index

[ ! -f $berkas_index ] && exit 0

# The root directory where the search will be performed
root_dir="$1/"

# Base URL for the API
url="http://$2"

# Checks if the root directory exists
if [ ! -d "$root_dir" ]; then
    echo "Direktori $root_dir tidak ada!"
    exit 1
fi

# Search all directories in the $root_dir directory except 'references' or 'references'
find "$root_dir" -type d ! -path '*referen*' | while read -r dir; do
    # Check if the metadata.db file exists in the directory
    if [ -f "$dir/metadata.db" ]; then
        # Save the name of the directory that has metadata.db
        calibre_dir=$dir

	# Defines files for title, author, series, and tags
	# as well as deleting existing data and downloading new data
        for type in titles authors series tags publishers; do

            # remove all occurrences of data/ from the caliber_dir variable
            calibre_dir_current=${calibre_dir#data/}                         
                        	
            # add root data directory
            berkas="$calibre_dir/$type.json"
            
            # delete previous file
            [ -f "$berkas" ] && rm -f "$berkas"
            
            # run query
            export QUERY_STRING="$type=1&api&db=$calibre_dir_current"
            export REQUEST_METHOD="GET"
            echo "${QUERY_STRING} > $berkas"
            ./ugai.cgi > "$berkas"
		
            # Escape special characters that may be in $file
            escaped_calibre_dir=$(echo "$calibre_dir" | sed 's|[\/&]|\\&|g')
            sed -i "s|$escaped_calibre_dir||g" "$berkas"
            
            # remove process residue
            sed -i '1d' $berkas
        done
    fi
done

# delete the index.txt file
rm -f ${berkas_index}

# delete OPF
#find /mnt/usb/ugai/www/data -type f \( -name "*.opf" \) -exec rm -f {} \;

# secure directories by creating index.html in all directories
#find /mnt/usb/ugai/www/data -type d ! -path '*kamus*' -exec sh -c 'test ! -f "$1/index.html" && touch "$1/index.html"' _ {} \;

# secure
#chmod -R 755 /mnt/usb/ugai/www/data

# restart
reboot

