# uhttpd webserver configuration
# to run with ugai.cgi
# Script by: Sri Sutyoko Hermawan
# 2023.5

config uhttpd main
list listen_http        0.0.0.0:80
# list listen_http        [::]:80
# HTTPS listen addresses, multiple allowed
#list listen_https       0.0.0.0:443
# list listen_https       [::]:443
option home             /mnt/usb/www
option index_page       "index.cgi index.html"
option rfc1918_filter 1
option max_requests 50
option cert             /etc/uhttpd.crt
option key              /etc/uhttpd.key
option cgi_prefix       /cgi-bin
#enable to run ugai.cgi outside cgi-bin
list interpreter        ".cgi=/mnt/usb/www/ugai.cgi"
option script_timeout   60
option network_timeout  30
option tcp_keepalive    1
option realm    Komugai
config cert px5g
option days             730
option bits             1024
option country          ID
option state            Jakarta
option location         Jakarta
option commonname       Komugai

